version: "3.8"

services:

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filedb
    ports:
      - "5434:5432"

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/filedb
      SECRET_KEY: supersecretkey123
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ENCRYPTION_KEY: px-4BbBStJ8-kXo8wTQd1K1ShV8OglRLYzN5jxkGqrk=
      MAIL_PORT: 587
      MAIL_USERNAME: sarjanpratap@gmail.com
      MAIL_PASSWORD: sarjan@4051
      MAIL_SERVER: smtp.gmail.com
      MAIL_FROM: sarjanpratap@gmail.com
      MAIL_STARTTLS: "True"
      MAIL_SSL_TLS: "False"
